routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::group(['as'=>'site.','namespace'=>'Site'],function (){
    Route::get('public-albums','AlbumController@index');
    Route::get('profile','ProfileController@show');
    Route::get('profile-albums','ProfileController@privateAlbums');
    Route::post('add-album','ProfileController@addAlbum');
    Route::post('edit-album/{id}','ProfileController@editAlbum');
    Route::get('delete-album','ProfileController@delAlbum');
});

Route::group(['as'=>'dashboard.','prefix'=>'dashboard','namespace'=>'Admin'], function () {
    Route::get('logout',function (){
        admin()->logout();
        return redirect()->route('dashboard.login');
    });
    Route::view('login','admin.login')->middleware('guest');
    Route::post('login','HomeController@login')->name('login');
    Route::group(['middleware'=>'Admin'],function (){
        Route::get('/','HomeController@index')->name('main');
        Route::resource('admins','AdminController');
        Route::resource('users','UserController');
        Route::resource('albums','AlbumController');
    });
});
Route::view('/', 'website.home');
Route::view('profile', 'website.profile');

app/Album.php
<?php

namespace App;

use App\Http\Traits\ImageOps;
use App\Http\Traits\LangOps;
use Illuminate\Database\Eloquent\Model;

class Album extends Model
{
    use ImageOps,LangOps;
    protected $guarded = ['id'];
    public $timestamps = ['created_at','updated_at'];

    public function photos()
    {
        return $this->hasMany(AlbumImage::class,'album_id');
    }

    public function getPriceAfterDiscountAttribute()
    {
        return $this->price - $this->price*$this->discount_percentage/100;
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/AlbumController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Album;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AlbumController extends Controller
{
    public function index()
    {
        if (!\admin()->user()->_can('read albums')){
            popup(['warning'=>'no permission to pass here']);
            return back();
        }

        $albums = Album::with('photos')->paginate(10);
        return view('admin.albums.index',compact('albums'));
    }

    public function destroy($id)
    {
        if (!\admin()->user()->_can('delete admins')){
            popup(['warning'=>'no permission to pass here']);
            return back();
        }

        Album::find($id)->delete();
        popup('delete');
        return back();
    }
}

app/Http/Controllers/Site/AlbumController.php
<?php

namespace App\Http\Controllers\Site;

use App\Album;
use App\Http\Resources\Site\AlbumResource;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AlbumController extends Controller
{
    public function index()
    {
        $albums = Album::whereType('public')->paginate(6);
        return response()->json(new AlbumResource($albums));
    }
}

resources/views/admin/albums/index.blade.php
@extends('admin.layout.master')
@push('title','Admins')

@section('content')
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th>Name (ar)</th>
                <th>Name (en)</th>
                <th>Main Image</th>
                <th>Type</th>
                <th>Price</th>
                <th>Discount Percentage</th>
                <th>Owner</th>
                <th>Album Images</th>
                <th class="text-center" style="width: 30px;"><i class="icon-menu-open2"></i></th>
            </tr>
            </thead>
            <tbody>
            @foreach($albums as $album)
                <tr>
                    <td>{{$album->ar_name}}</td>
                    <td>{{$album->en_name}}</td>
                    <td>
                        <img src="{{$album->image}}" width="50" height="50">
                    </td>
                    <td>{{$album->type}}</td>
                    <td>{{$album->price}}</td>
                    <td>{{$album->discount_percentage}}</td>
                    <td>{{$album->user->name}}</td>
                    <td>
                        <a href="{{route('dashboard.albums.show',$album->id)}}"  data-toggle="modal" data-target="#exampleModal{{$album->id}}" class="btn btn-info">Show Album</a>
                    </td>
                    <td class="text-center">
                        <ul class="icons-list">
{{--                            <li><a href="{{route('dashboard.albums.edit',$album->id)}}" data-popup="tooltip" title="Edit"><i class="icon-pencil7"></i></a></li>--}}
                            <li><a href="javascript:" class="delete" data-del="{{$album->id}}" data-popup="tooltip" title="Remove"><i class="icon-trash"></i></a></li>
                        </ul>
                        <form action="{{route('dashboard.albums.destroy',$album->id)}}" class="delete{{$album->id}}" method="post">
                            @csrf
                            @method('DELETE')
                        </form>
                        <div class="modal fade" id="exampleModal{{$album->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Photos</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                                            <ol class="carousel-indicators">
                                                @foreach($album->photos as $key=>$photo)
                                                <li data-target="#carouselExampleIndicators" data-slide-to="{{$key}}" class="{{$key == 0 ?'active' : ''}}"></li>
                                                    @endforeach
                                            </ol>
                                            <div class="carousel-inner">
                                                @foreach($album->photos as $key=>$photo)
                                                <div class="carousel-item {{$key == 0 ?'active' : ''}}">
                                                    <img class="d-block w-100" src="{{$photo->image}}" alt="First slide">
                                                </div>
                                                    @endforeach
                                            </div>
                                            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                                <span class="sr-only">Previous</span>
                                            </a>
                                            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                                <span class="sr-only">Next</span>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="button" class="btn btn-primary">Save changes</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {!! $albums->links() !!}
    </div>
    <script>
        $('.delete').click(function () {
            alert('ss');
            $('.delete'+$(this).data('del')).submit();
        })
    </script>
@endsection