routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::group(['as'=>'site.','namespace'=>'Site'],function (){
    Route::get('public-albums','AlbumController@index');
    Route::get('profile','ProfileController@show');
    Route::get('profile-albums','ProfileController@privateAlbums');
    Route::post('add-album','ProfileController@addAlbum');
    Route::post('edit-album/{id}','ProfileController@editAlbum');
    Route::get('delete-album','ProfileController@delAlbum');
});

Route::group(['as'=>'dashboard.','prefix'=>'dashboard','namespace'=>'Admin'], function () {
    Route::get('logout',function (){
        admin()->logout();
        return redirect()->route('dashboard.login');
    });
    Route::view('login','admin.login')->middleware('guest');
    Route::post('login','HomeController@login')->name('login');
    Route::group(['middleware'=>'Admin'],function (){
        Route::get('/','HomeController@index')->name('main');
        Route::resource('admins','AdminController');
        Route::resource('users','UserController');
        Route::resource('albums','AlbumController');
    });
});
Route::view('/', 'website.home');
Route::view('profile', 'website.profile');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Str;

class User extends Authenticatable
{
    use Notifiable;
    protected $guarded = ['id'];
    public $timestamps = ['created_at','updated_at'];

    public function albums()
    {
        return $this->hasMany(Album::class,'user_id');
    }

    public function privateAlbums()
    {
        return $this->hasMany(Album::class,'user_id')->where('type','private');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Admin;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (!\admin()->user()->_can('read users')){
            popup(['warning'=>'no permission to pass here']);
            return back();
        }

        $users = User::paginate(10);
        return view('admin.users.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!\admin()->user()->_can('create users')){
            popup(['warning'=>'no permission to pass here']);
            return back();
        }

        return  view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = popup(['rules'=>[
            'name'=>'required',
            'email'=>'required|email|unique:users,email',
            'password'=>'required|confirmed|min:6'
        ]]);
        if ($validate)
            return back()->withInput($request->all());
        $inputs = $request->all();
        $inputs['password'] = bcrypt($request->password);
        User::create($inputs);
        popup('add');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (!\admin()->user()->_can('delete users')){
            popup(['warning'=>'no permission to pass here']);
            return back();
        }

        if ($id != \admin()->id()){
            User::find($id)->delete();
            popup('delete');
        }else{
            popup(['warning'=>'Cant Delete Your Account']);
        }
        return back();

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!\admin()->user()->_can('update users')){
            popup(['warning'=>'no permission to pass here']);
            return back();
        }
        $user = User::find($id);
        return view('admin.users.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = popup(['rules'=>[
            'name'=>'required',
            'email'=>'required|email|unique:users,email',
            'password'=>'nullable|min:6|confirmed'
        ]]);
        if ($validate)
            return back()->withInput($request->all());
        $inputs = $request->except('password','password_confirmation');
        if ($request->has('password') && $request->password != null)
            $inputs['password'] = bcrypt($request->password);

        User::find($id)->update($inputs);
        popup('update');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layout.master')
@push('title','Users | Create')
@section('content')
<div class="panel">
    <div class="panel-body">
        {!! Form::open(['route' => 'dashboard.users.store', 'method' => 'post']) !!}
        @csrf
        @include('admin.users.form')
        {!! Form::close() !!}
    </div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layout.master')
@push('title','Admins | Update')
@section('content')
    <div class="panel">
        <div class="panel-body">
            {!! Form::model($user, ['route' => ['dashboard.users.update', $user->id], 'method' => 'PUT']) !!}
            @csrf
            @include('admin.users.form')

            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/users/form.blade.php
<fieldset class="content-group">
    <div class="form-group">
        <label class="control-label col-lg-2">Name :</label>
        <div class="col-lg-10">
            {!! Form::text('name',null, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-lg-2">Email :</label>
        <div class="col-lg-10">
            {!! Form::email('email',null, ['class' => 'form-control','placeholder'=>'Example@example.com']) !!}
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-lg-2">Password</label>
        <div class="col-lg-10">
            <input type="password" name="password" class="form-control">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-lg-2">Password Confirmation</label>
        <div class="col-lg-10">
            <input type="password" name="password_confirmation" class="form-control">
        </div>
    </div>
    <br>
</fieldset>




<div class="form-group">
    <div class="col-lg-4 col-lg-offset-4">
        <input type="submit" value="Save" class="form-control btn btn-success">
    </div>
</div>

resources/views/admin/users/index.blade.php
@extends('admin.layout.master')
@push('title','Users')

@section('content')
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th class="text-center" style="width: 30px;"><i class="icon-menu-open2"></i></th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
            <tr>
                <td>{{$user->name}}</td>
                <td>{{$user->email}}</td>
                <td class="text-center">
                    <ul class="icons-list">
                        <li><a href="{{route('dashboard.users.edit',$user->id)}}" data-popup="tooltip" title="Edit"><i class="icon-pencil7"></i></a></li>
                        <li><a href="{{route('dashboard.users.show',$user->id)}}" data-popup="tooltip" title="Remove"><i class="icon-trash"></i></a></li>
                    </ul>
                </td>
            </tr>
                @endforeach
            </tbody>
        </table>
        {!! $users->links() !!}
    </div>

@endsection