routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::group(['as'=>'site.','namespace'=>'Site'],function (){
    Route::get('public-albums','AlbumController@index');
    Route::get('profile','ProfileController@show');
    Route::get('profile-albums','ProfileController@privateAlbums');
    Route::post('add-album','ProfileController@addAlbum');
    Route::post('edit-album/{id}','ProfileController@editAlbum');
    Route::get('delete-album','ProfileController@delAlbum');
});

Route::group(['as'=>'dashboard.','prefix'=>'dashboard','namespace'=>'Admin'], function () {
    Route::get('logout',function (){
        admin()->logout();
        return redirect()->route('dashboard.login');
    });
    Route::view('login','admin.login')->middleware('guest');
    Route::post('login','HomeController@login')->name('login');
    Route::group(['middleware'=>'Admin'],function (){
        Route::get('/','HomeController@index')->name('main');
        Route::resource('admins','AdminController');
        Route::resource('users','UserController');
        Route::resource('albums','AlbumController');
    });
});
Route::view('/', 'website.home');
Route::view('profile', 'website.profile');

resources/views/admin/admins/create.blade.php
@extends('admin.layout.master')
@push('title','Admins | Create')
@section('content')
<div class="panel">
    <div class="panel-body">
        {!! Form::open(['route' => 'dashboard.admins.store', 'method' => 'post']) !!}
        @csrf
        @include('admin.admins.form')
        {!! Form::close() !!}
    </div>
</div>
@endsection

resources/views/admin/admins/edit.blade.php
@extends('admin.layout.master')
@push('title','Admins | Update')
@section('content')
    <div class="panel">
        <div class="panel-body">
            {!! Form::model($admin, ['route' => ['dashboard.admins.update', $admin->id], 'method' => 'PUT']) !!}
            @csrf
            @include('admin.admins.form')

            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/admins/form.blade.php
<fieldset class="content-group">
    <div class="form-group">
        <label class="control-label col-lg-2">Email :</label>
        <div class="col-lg-10">
            {!! Form::email('email',null, ['class' => 'form-control','placeholder'=>'Example@example.com']) !!}
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-lg-2">Password</label>
        <div class="col-lg-10">
            <input type="password" name="password" class="form-control">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-lg-2">Password Confirmation</label>
        <div class="col-lg-10">
            <input type="password" name="password_confirmation" class="form-control">
        </div>
    </div>
    <br>
</fieldset>



<fieldset class="content-group">
    <h1>Permissions</h1>
    @foreach(\App\Permission::with('rules')->get() as $permission)
        <div class="form-group">
            <label class="control-label col-lg-2">{{$permission->name}}</label>
            <div class="col-lg-10">
                {!! Form::select('permission[]', $permission->rules->mapWithKeys(function ($q){
                    return [$q->id => $q->name];
                })
     , isset($admin) ? myPerm($admin->permissions(),$permission->name) : null , ['class' => 'form-control bootstrap-select','multiple']) !!}
            </div>
        </div>
    @endforeach
</fieldset>


<div class="form-group">
    <div class="col-lg-4 col-lg-offset-4">
        <input type="submit" value="Save" class="form-control btn btn-success">
    </div>
</div>

resources/views/admin/admins/index.blade.php
@extends('admin.layout.master')
@push('title','Admins')

@section('content')
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th>Email</th>
                <th class="text-center" style="width: 30px;"><i class="icon-menu-open2"></i></th>
            </tr>
            </thead>
            <tbody>
            @foreach($admins as $admin)
                <tr>
                    <td>{{$admin->email}}</td>
                    <td class="text-center">
                        <ul class="icons-list">
                            @if(canDo($permissions,'update admins'))
                                <li><a href="{{route('dashboard.admins.edit',$admin->id)}}" data-popup="tooltip" title="Edit"><i class="icon-pencil7"></i></a></li>
                            @endif
                            @if(canDo($permissions,'read admins'))
                                <li><a href="{{route('dashboard.admins.show',$admin->id)}}" class="delete" data-del="{{$admin->id}}" data-popup="tooltip" title="Remove"><i class="icon-trash"></i></a></li>
                            @endif
                        </ul>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {!! $admins->links() !!}
    </div>

@endsection
@push('header')
@endpush