routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::group(['as'=>'site.','namespace'=>'Site'],function (){
    Route::get('public-albums','AlbumController@index');
    Route::get('profile','ProfileController@show');
    Route::get('profile-albums','ProfileController@privateAlbums');
    Route::post('add-album','ProfileController@addAlbum');
    Route::post('edit-album/{id}','ProfileController@editAlbum');
    Route::get('delete-album','ProfileController@delAlbum');
});

Route::group(['as'=>'dashboard.','prefix'=>'dashboard','namespace'=>'Admin'], function () {
    Route::get('logout',function (){
        admin()->logout();
        return redirect()->route('dashboard.login');
    });
    Route::view('login','admin.login')->middleware('guest');
    Route::post('login','HomeController@login')->name('login');
    Route::group(['middleware'=>'Admin'],function (){
        Route::get('/','HomeController@index')->name('main');
        Route::resource('admins','AdminController');
        Route::resource('users','UserController');
        Route::resource('albums','AlbumController');
    });
});
Route::view('/', 'website.home');
Route::view('profile', 'website.profile');

resources/views/admin/layout/footer.blade.php
<!-- Footer -->
<div class="footer text-muted">
    &copy; 2019. <a href="#">Cinema Developed</a> by <a href="https://www.linkedin.com/in/youssef-magdy-a86018171/" target="_blank">Youssef Magdy</a>
</div>
<!-- /footer -->

resources/views/admin/layout/header.blade.php
<!-- Global stylesheets -->
<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
<link href="{{asset('admin/assets/css/icons/icomoon/styles.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('admin/assets/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('admin/assets/css/core.min.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('admin/assets/css/components.min.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('admin/assets/css/colors.min.css')}}" rel="stylesheet" type="text/css">
<!-- /global stylesheets -->

<!-- Core JS files -->
<script type="text/javascript" src="{{asset('admin/assets/js/plugins/loaders/pace.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/assets/js/core/libraries/jquery.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/assets/js/core/libraries/bootstrap.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/assets/js/plugins/loaders/blockui.min.js')}}"></script>
<!-- /core JS files -->
<script type="text/javascript" src="{{asset('admin/assets/js/plugins/forms/selects/bootstrap_select.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/assets/js/pages/form_bootstrap_select.js')}}"></script>

<!-- Theme JS files -->
<script type="text/javascript" src="{{asset('admin/assets/js/plugins/visualization/d3/d3.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/assets/js/plugins/visualization/d3/d3_tooltip.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/assets/js/plugins/forms/styling/switchery.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/assets/js/plugins/forms/styling/uniform.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/assets/js/plugins/forms/selects/bootstrap_multiselect.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/assets/js/plugins/ui/moment/moment.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/assets/js/plugins/pickers/daterangepicker.js')}}"></script>

<script type="text/javascript" src="{{asset('admin/assets/js/core/app.min.js')}}"></script>
{{--<script type="text/javascript" src="{{asset('admin/assets/js/pages/dashboard.js')}}"></script>--}}

<!-- /theme JS files -->
<style>
    .icons-list li {
        float: left;
    }

    .icons-list li a {
        display: block;
        padding: 5px;
    }
</style>

resources/views/admin/layout/master.blade.php
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dashboard | @stack('title')</title>

    @include('admin.layout.header')
    @stack('header')

</head>

<body>

@include('admin.layout.nav')

<!-- Page container -->
<div class="page-container">

    <!-- Page content -->
    <div class="page-content">

        @include('admin.layout.side_bar')
        <!-- Main content -->
        <div class="content-wrapper">

            <!-- Page header -->
            <div class="page-header page-header-default">
                <div class="page-header-content">
                    <div class="page-title">
                        <h4><i class="icon-arrow-right6 position-left"></i> <span class="text-semibold">@stack('title')</span> - Dashboard</h4>
                    </div>
                </div>

                <div class="breadcrumb-line">
                    <ul class="breadcrumb">
                        <li><i class="icon-home2 position-left"></i> @stack('title')</li>
                        <li class="active"><a href="{{url('dashboard')}}">Dashboard</a></li>
                    </ul>
                </div>
            </div>
            <!-- /page header -->


            <!-- Content area -->
            <div class="content">
                @yield('content')
                @include('admin.layout.footer')
                <script src="{{asset('admin/assets/js/plugins/notifications/sweet_alert.min.js')}}"></script>
                @include('sweet::alert')
            </div>
            <!-- /content area -->
        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</div>
<!-- /page container -->

</body>
</html>

resources/views/admin/layout/nav.blade.php
<!-- Main navbar -->
<div class="navbar navbar-inverse">
    <div class="navbar-header">
        <a class="navbar-brand" href="index.html"><img src="{{asset('admin/assets/images/logo_light.png')}}" alt=""></a>

        <ul class="nav navbar-nav visible-xs-block">
            <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
            <li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
        </ul>
    </div>

    <div class="navbar-collapse collapse" id="navbar-mobile">
        <ul class="nav navbar-nav">
            <li><a class="sidebar-control sidebar-main-toggle hidden-xs"><i class="icon-paragraph-justify3"></i></a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown dropdown-user">
                <a class="dropdown-toggle" data-toggle="dropdown">
                    <img src="{{asset('admin/assets/images/placeholder.jpg')}}" alt="">
                    <span>{{admin()->user()->email}}</span>
                    <i class="caret"></i>
                </a>

                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="{{route('dashboard.logout')}}"><i class="icon-switch2"></i> Logout</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>
<!-- /main navbar -->

resources/views/admin/layout/side_bar.blade.php
<!-- Main sidebar -->
<div class="sidebar sidebar-main">
    <div class="sidebar-content">


        <!-- Main navigation -->
        <div class="sidebar-category sidebar-category-visible">
            <div class="category-content no-padding">
                <ul class="navigation navigation-main navigation-accordion">

                    <!-- Main -->
                    <li class="navigation-header"><span>Main</span> <i class="icon-menu" title="Main pages"></i></li>
                    <li class="{{request()->is('*dashboard') ? 'active' : ''}}"><a href="{{route('dashboard.main')}}"><i class="icon-home4"></i> <span>Dashboard</span></a></li>
                    @if(canDo($permissions,'read users'))
                    <li>
                        <a href="#" class="{{request()->is('*users*') ? 'active' : ''}}"><i class="icon-stack2"></i> <span>Users</span></a>
                        <ul>
                            <li class="{{request()->is('*users*') ? 'active' : ''}}"><a href="{{route('dashboard.users.index')}}">All Users</a></li>
                            @if(canDo($permissions,'create users'))
                            <li class="{{request()->is('*users/create') ? 'active' : ''}}"><a href="{{route('dashboard.users.create')}}">Add User</a></li>
                                @endif
                        </ul>
                    </li>
                    @endif
                    @if(canDo($permissions,'read admins'))
                    <li>
                        <a href="#" class="{{request()->is('*admins*') ? 'active' : ''}}"><i class="icon-stack2"></i> <span>Admins</span></a>
                        <ul>
                            <li class="{{request()->is('*admins*') ? 'active' : ''}}"><a href="{{route('dashboard.admins.index')}}">All Admins</a></li>
                            @if(canDo($permissions,'create users'))
                            <li class="{{request()->is('*admins/create') ? 'active' : ''}}"><a href="{{route('dashboard.admins.create')}}">Add Admin</a></li>
                                @endif
                        </ul>
                    </li>
                    @endif
                    @if(canDo($permissions,'read albums'))
                    <li>
                        <a href="#" class="{{request()->is('*albums*') ? 'active' : ''}}"><i class="icon-stack2"></i> <span>albums</span></a>
                        <ul>
                            <li class="{{request()->is('*albums*') ? 'active' : ''}}"><a href="{{route('dashboard.albums.index')}}">All albums</a></li>
                        </ul>
                    </li>
                        @endif
                </ul>
            </div>
        </div>
        <!-- /main navigation -->

    </div>
</div>
<!-- /main sidebar -->